from openpyxl import Workbook
import os

def create_basic_xlsx(filename: str, task_title: str, task_description: str):
    wb = Workbook()
    ws = wb.active
    ws.title = "Task Summary"

    ws["A1"] = "Task Title"
    ws["B1"] = task_title

    ws["A2"] = "Description"
    ws["B2"] = task_description

    ws["A4"] = "Status"
    ws["B4"] = "Generated by Agentic Dev Studio"

    file_path = f"/tmp/{filename}"
    wb.save(file_path)
    return file_path
