"""Experience store for continuous learning and semantic retrieval."""

from __future__ import annotations

import hashlib
import math
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any


@dataclass(slots=True, frozen=True)
class ExperienceRecord:
    """Captured execution experience generated by autonomous runs."""

    kind: str
    payload: dict[str, Any]
    embedding: list[float]
    timestamp: str


class ExperienceStore:
    """In-memory continuous learning store with vector-style retrieval."""

    def __init__(self, *, embedding_dimensions: int = 48) -> None:
        self.embedding_dimensions = max(8, embedding_dimensions)
        self._records: list[ExperienceRecord] = []

    def _embed(self, text: str) -> list[float]:
        digest = hashlib.sha256(text.encode("utf-8")).digest()
        return [digest[i % len(digest)] / 255.0 for i in range(self.embedding_dimensions)]

    def _store(self, kind: str, payload: dict[str, Any]) -> ExperienceRecord:
        record = ExperienceRecord(
            kind=kind,
            payload=payload,
            embedding=self._embed(f"{kind}:{payload}"),
            timestamp=datetime.now(timezone.utc).isoformat(),
        )
        self._records.append(record)
        return record

    def store_task_outcome(self, task_id: str, outcome: dict[str, Any]) -> ExperienceRecord:
        return self._store("task_outcome", {"task_id": task_id, "outcome": outcome})

    def store_agent_decision(self, decision: dict[str, Any]) -> ExperienceRecord:
        return self._store("agent_decision", decision)

    def store_success_metrics(self, metrics: dict[str, Any]) -> ExperienceRecord:
        return self._store("success_metrics", metrics)

    def store_execution_trace(self, trace: dict[str, Any]) -> ExperienceRecord:
        return self._store("execution_trace", trace)

    def store_evaluation(self, evaluation: dict[str, Any]) -> ExperienceRecord:
        return self._store("evaluation", evaluation)

    def query_similar(self, text: str, *, limit: int = 5, kinds: set[str] | None = None) -> list[ExperienceRecord]:
        if not self._records:
            return []

        query_embedding = self._embed(text)

        def cosine(a: list[float], b: list[float]) -> float:
            numerator = sum(x * y for x, y in zip(a, b, strict=False))
            a_norm = math.sqrt(sum(x * x for x in a))
            b_norm = math.sqrt(sum(y * y for y in b))
            if a_norm == 0 or b_norm == 0:
                return 0.0
            return numerator / (a_norm * b_norm)

        filtered = self._records
        if kinds:
            filtered = [record for record in self._records if record.kind in kinds]

        ranked = sorted(filtered, key=lambda record: cosine(query_embedding, record.embedding), reverse=True)
        return ranked[: max(1, limit)]

    def all_records(self) -> list[ExperienceRecord]:
        return list(self._records)
